"use client";

import { useQuery } from "@tanstack/react-query";
import { ClockCounterClockwise, NewspaperClipping, Repeat } from "@phosphor-icons/react";

import { AppButton, AppPage, EmptyState, InlineError, LoadingRows, Panel, PanelHeader, StatusPill } from "@/components/AppPage";
import { api } from "@/lib/api/client";
import { formatDateTime } from "@/lib/format";

export default function BriefingPage() {
  const latest = useQuery({
    queryKey: ["briefing", "latest"],
    queryFn: () => api.getLatestBriefing(),
    retry: false,
  });
  const history = useQuery({
    queryKey: ["briefing", "history"],
    queryFn: () => api.listBriefings(20),
  });

  const refresh = () => {
    latest.refetch();
    history.refetch();
  };
  const latestError = latest.error instanceof Error ? latest.error.message : "";
  const noBriefing = latestError.startsWith("404");

  return (
    <AppPage
      eyebrow="Briefing"
      title="Latest and history"
      description="Read stored daily briefings generated by the worker."
      actions={
        <AppButton
          onClick={refresh}
          variant="secondary"
          size="sm"
        >
          <Repeat size={14} weight="bold" /> Refresh
        </AppButton>
      }
    >
      <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_22rem]">
        <Panel>
          <PanelHeader title="Latest briefing" />
          {latest.isLoading && <LoadingRows rows={4} />}
          {latest.error && !noBriefing && !latest.isLoading && <div className="p-4"><InlineError message={latestError} /></div>}
          {noBriefing && !latest.isLoading && (
            <EmptyState
              icon={<NewspaperClipping size={20} />}
              title="No briefing yet"
              body="The history will fill in after the worker stores its first briefing."
            />
          )}
          {latest.data && (
            <article className="p-5">
              <div className="flex flex-wrap items-center gap-2">
                <StatusPill tone={latest.data.document_count > 0 ? "success" : "neutral"}>
                  {latest.data.document_count} document{latest.data.document_count === 1 ? "" : "s"}
                </StatusPill>
                <span className="text-xs text-muted-foreground">
                  Generated {formatDateTime(latest.data.generated_at)}
                </span>
              </div>
              <h2 className="mt-4 text-lg font-semibold leading-7 tracking-tight text-foreground">
                {latest.data.summary}
              </h2>
              <div className="mt-4 grid gap-2 text-xs text-muted-foreground sm:grid-cols-2">
                <div className="rounded-lg bg-muted/50 p-3">
                  <p>Period start</p>
                  <p className="mt-1 font-mono text-foreground">{formatDateTime(latest.data.period_start)}</p>
                </div>
                <div className="rounded-lg bg-muted/50 p-3">
                  <p>Period end</p>
                  <p className="mt-1 font-mono text-foreground">{formatDateTime(latest.data.period_end)}</p>
                </div>
              </div>
              <pre className="mt-5 whitespace-pre-wrap rounded-lg bg-muted/40 p-4 font-sans text-sm leading-6 text-foreground">
                {latest.data.body_markdown}
              </pre>
            </article>
          )}
        </Panel>

        <Panel>
          <PanelHeader title="History" />
          {history.isLoading && <LoadingRows rows={5} />}
          {history.error && !history.isLoading && (
            <div className="p-4">
              <InlineError message={history.error instanceof Error ? history.error.message : "Briefing history failed"} />
            </div>
          )}
          {history.data?.briefings.length === 0 && (
            <EmptyState icon={<ClockCounterClockwise size={20} />} title="No history" />
          )}
          {history.data && history.data.briefings.length > 0 && (
            <div className="divide-y divide-border">
              {history.data.briefings.map((briefing) => (
                <div key={briefing.id} className="px-4 py-3">
                  <div className="flex items-start justify-between gap-3">
                    <p className="min-w-0 text-sm font-semibold leading-5 text-foreground">
                      {briefing.summary}
                    </p>
                    <span className="shrink-0 font-mono text-[11px] text-muted-foreground">
                      #{briefing.id}
                    </span>
                  </div>
                  <p className="mt-1 text-xs text-muted-foreground">
                    {formatDateTime(briefing.generated_at)} / {briefing.document_count} docs
                  </p>
                </div>
              ))}
            </div>
          )}
        </Panel>
      </div>
    </AppPage>
  );
}
